disabled_rules:
  - cyclomatic_complexity
  - function_body_length
  - discarded_notification_center_observer
  - type_body_length
  - nesting
  - large_tuple
  - function_parameter_count
  - trailing_whitespace
  - void_return
  - closure_end_indentation
  - trailing_comma
  - todo
  
opt_in_rules:
  - force_unwrapping
  - closure_end_indentation
  - sorted_imports
  - unneeded_parentheses_in_closure_argument
  
excluded:
  - Pods

warning_threshold: 1

line_length:
  warning: 120
  error: 120
  ignores_urls: true
  ignores_comments: true
  
file_length:
  warning: 1000
  error: 2000
  
identifier_name:
  min_length: 2
  max_length: 60
  
type_name:
  min_length: 2
  max_length: 60

force_unwrapping:
  error

#Будет ошибка при принудительном касте типов
force_cast:
  error
  
#Ошибка при точке с запятой на конце
trailing_semicolon:
  error
  
#Будет ошибка при излишних скобках
control_statement:
  error

#Будет ошибка при лишнем указании getter-a
implicit_getter:
  error

#Будет ошибка, если параметры метода расположены вертикально и не из одной табуляции
vertical_parameter_alignment:
  error

#Будет ошибка при отсутствии нужных пробелов при указании возвращаемого значения
return_arrow_whitespace:
  error

#Будет ошибка при лишнем упоминании неиспользуемых объектов
unused_optional_binding:
  error

#Будет ошибка при указании уточненных типов массивов и словарей в устаревших форматах
syntactic_sugar:
  error
